### ISSUE TITLE
Keyboard locks up during game play :

### ISSUE THREAD

**Issue by jun-bun** [chinatsu/c2lina#7]
OS : 10.14.6  latest patches
Macbook pro 13 retina late 2013

client : All clients tested so far, including original, mac builds from 120 - 240 WIP, older builds, blur and no blur.

behavior: keyboard does not accept keypress or is very delayed with keypresses.
reproducible ? : It randomly happens but is guaranteed to happen if you play long enough, seems to happen more frequently with single-player modes than room battles.

The only error i see so far is this : but am not sure if this is the issue.

java[3173:413595] *** Assertion failure in -[NSEvent _cgsEventRecord], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.60.109/AppKit.subproj/NSEvent.m:1986
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Non-Java exception raised, not handled! (Original problem: Deprecated in 10_12... DO NOT EVER USE CGSEventRecord directly. Bad things, man.... bad things.)
at apple.awt.ComponentModel._handleEvent(Native Method)
	at apple.awt.ComponentModel.handleEvent(ComponentModel.java:273)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:753)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1000)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:865)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:686)
	at java.awt.Component.dispatchEventImpl(Component.java:4648)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by chinatsu** [comment]
After some rubber duck debugging, I think the current theory is that it's a deterministic sequence of inputs that cause the application to stop listening to more inputs. It seems also reversible, though I'm not sure if it's just about repeating the same inputs that made it stop listening, or if it's something else

**Comment by jun-bun** [comment]
Fixed by disabling Apple Press and Hold
Via terminal
defaults write -g ApplePressAndHoldEnabled -bool false
